### ISSUE TITLE
Problem with polish (programmer) keyboard

### ISSUE THREAD

**Issue by RoboWeb** [atom/atom-keymap#187] opened 2016-11-22 08:20 UTC
Hi! After update Atom to v. 1.12.4 and deprecation package "keyboard-localisation" - polish keyboard localisation dsn't work. I have MSWin10 O.S.. More specifically - in Editor:
AltGr+a, and AltGr+A | Expectation: "ą" and "Ą" | in Atom "ą", "Ą" - OK
AltGr+c | Expectation: "ć" | in Atom "ć" - OK
AltGr+C | Expectation: "Ć" | in Atom "" - no reaction
AltGr+e, AltGr+E | Exp: "ę", "Ę" | Atom: "ę", "Ę" - OK
AltGr+l, AltGr+L | Exp: "ł", "Ł" | Atom: "ł", "Ł" - OK
AltGr+n, AltGr+N | Exp: "ń", "Ń" | Atom: "ń", "Ń" - OK
AltGr+o | Exp: "ó" | Atom: "Open Folder" - (so it also works AltGr+Ctrl+o = "Open Folder")
AltGr+O | Exp: "Ó" | Atom "Ó" - OK
AltGr+s, AltGr+S | Exp: "ś", "Ś" | Atom: "ś", "Ś" - OK
AltGr+z | Exp: "ż" | Atom: "Confirm Checkout HEAD revision" (AltGr+Ctrl+z)
AltGr+Z | Exp: "Ż" | Atom: "Ż" - OK
AltGr+x, AltGr+X | Exp: "ź", "Ź" | Atom: "ź", "Ź" - OK

Summary:
AltGr+C - no reaction
AltGr+o - "Open Folder", (should be only AltGr+Ctrl+o)
AltGr+z - "Confirm Checkout HEAD revision"

(hmmm... :) - not bad... but I need this letters/chars :)
img with polish programmer keyboard localisation:
![pl-programmers](https://cloud.githubusercontent.com/assets/5095442/20516042/bc07d28c-b094-11e6-914d-017d8e50d98f.png)

**Comment by Ben3eeE** [comment] 2016-11-22 08:24
For <kbd>AltGr+o</kbd> and <kbd>AltGr+z</kbd> and Atom 1.12 this is expected. The keys are bound to `editor:checkout-head-revision` and `application:add-project-folder`. These keybindings are removed or moved in Atom 1.13. We did not want to change this in a hotfix release of Atom 1.12.

So your solution is to either unset these keybindings in Atom 1.12 or to run Atom beta.  To unset the keybindings add the following to your `keymap.cson` which you can reach from the file menu. File -> Keymap...

```cson
'atom-workspace atom-text-editor:not([mini])':
  'ctrl-alt-z': 'unset!'
 
'body':
  'ctrl-alt-o': 'unset!'
```

For AltGr+c can you open the keybinding resolver and show the results you see when pressing this combination? You can open the keybinding resolver using <kbd>Ctrl+.</kbd>.

**Comment by RoboWeb** [comment] 2016-11-22 08:33
Thx for reply.
For AltGr+c keybinding resolver show me:
![keybindingresolver](https://cloud.githubusercontent.com/assets/5095442/20516350/767a6ef8-b096-11e6-8e72-914a78e1f726.png)

Why AltGr+[something] = AltGr+Ctrl+[something] ?
I try AltGr+c and AltGr+Ctrl+c and keybinding resolver show me exactly this same.

**Comment by Ben3eeE** [comment] 2016-11-22 08:39
On Windows <kbd>Ctrl-Alt</kbd>=<kbd>AltGr</kbd> so without the use of third party tools or some workaround a shortcut like <kbd>AltGr+Ctrl</kbd> will not work on Windows.

**Comment by Ben3eeE** [comment] 2016-11-22 08:56
I can not reproduce the problem with <kbd>AltGr-c</kbd>.

* Did you change keyboard layout while Atom was running?
* Try completely exiting Atom and starting it using `atom --safe`.

**Comment by RoboWeb** [comment] 2016-11-22 09:10
thx
I add in keymap.cson this, and its works:
<pre>'atom-workspace atom-text-editor:not([mini])':
  'ctrl-alt-z': 'unset!'
  'alt-c': 'ć'

'body':
  'ctrl-alt-o': 'unset!'</pre>

**Comment by RoboWeb** [comment] 2016-11-22 09:23
> Did you change keyboard layout while Atom was running?

I do not change any keyboard layout

> Try completely exiting Atom and starting it using atom --safe

I run in this mode (of corese: remove before my changes in keymap.cson) and AltGr-c works properly...

**Comment by Ben3eeE** [comment] 2016-11-22 09:43
Do you still have `keyboard-localization` installed? Can you try disabling or uninstalling that and then restart Atom to see if <kbd>AltGr-c</kbd> works?

**Comment by RoboWeb** [comment] 2016-11-22 09:58
I disabled it before. Now I uninstall <code>keyboard-localisation</cody> tottaly... Now <kbd>AltGr-c</kbd> works corectly, but <kbd>AltGr-C</kbd> conflicting with css-minifier... :)
![keybindingresolver-2](https://cloud.githubusercontent.com/assets/5095442/20519228/66f49ccc-b0a2-11e6-8220-f71410cf32e8.png)
...but I can handle it my self :)

thx

**Comment by Ben3eeE** [comment] 2016-11-22 10:08
You're welcome for the help. Closing this issue since everything seems to be working :slightly_smiling_face:

**Closed by Ben3eeE** 2016-11-22 10:08 UTC
Labels: more-information-needed

**Comment by pankuleczka** [comment] 2016-11-30 10:44
Let me just add that it seems the "Find in Current Buffer" input field also has problems with it's shortcuts (namely "Match Case" and "Only in Selection" triggering instead of a localised letters) - @Ben3eeE - is this also covered in 1.13? :)

**Comment by Ben3eeE** [comment] 2016-11-30 10:56
@damieng :point_up: regarding <kbd>Ctrl-Alt</kbd> bindings in `find-and-replace`.

**Comment by damieng** [comment] 2016-11-30 15:43
Yeah, we need to unbind those in find-and-replace. I couldn't find any sensible alternatives but am open to suggestions.

**Comment by damieng** [comment] 2016-11-30 18:09
PR for that at https://github.com/atom/find-and-replace/pull/822
