### ISSUE TITLE
Backspace does not work with Colemak keyboard layout

### ISSUE THREAD

**Issue by mattkang** [atom/atom-keymap#192] opened 2016-12-01 15:42 UTC
I use the Colemak layout as my primary input method on Windows 10. This layout remaps the caps lock key as backspace. Keymap does not recognize this remapping, and the backspace functionality does not work.

**Expected Behaviour:**
Press Caps Lock key to produce Backspace

**Observed Behaviour:**
Press Caps Lock key without result. When I press the Caps Lock key, the Key Binding Resolver recognizes it as Caps Lock (instead of Backspace) but does not toggle caps lock on/off.

I have noticed this since v1.12 of Atom. I am using the Colemak layout as provided [here](https://forum.colemak.com/topic/1621-colemak-for-windows-with-capslock-to-backspace/).

**Comment by Ben3eeE** [comment] 2016-12-01 15:54
Can you post the results of typing caps lock after running the following devtools console script:
```
document.addEventListener('keydown', e => console.log(e), true)
```

**Comment by Gert-dev** [comment] 2016-12-01 16:24
Here you go:

![test](https://cloud.githubusercontent.com/assets/6823929/20801994/e0d22308-b7ea-11e6-86eb-129da9dde5c3.png)

Interesting observation: `control + caps lock` _does_ work in the developer tools console. It doesn't in the text editor, though.

**Comment by mattkang** [comment] 2016-12-01 16:36
Yes I can confirm that Caps Lock as Backspace also works in the developer tools console but not the text editor. My results from keydown listener (practically identical):
![capture](https://cloud.githubusercontent.com/assets/2027430/20802564/6a774768-b7ba-11e6-872b-80500a85af94.PNG)

**Comment by Ben3eeE** [comment] 2016-12-01 16:41
For some reason the `key` and `code` fields are incorrectly resolved as `CapsLock`. Which confuses Atom because we use these fields when we resolve keys. 

You should be able to work around this issue using the [public keystroke resolver API](https://github.com/atom/atom-keymap/pull/164). If you try something like this to make <kbd>Ctrl-Caps Lock</kbd> resolve as `backspace`.

```coffee
atom.keymaps.addKeystrokeResolver ({event}) ->
  if event.key is 'CapsLock' and event.keyCode is 8 and event.ctrlKey and event.type is 'keydown'
    return 'backspace'
```

**Comment by mattkang** [comment] 2016-12-01 16:54
Thanks @Ben3eeE 

For the time being, I have achieved satisfactory behaviour from the following:
```coffee
atom.keymaps.addKeystrokeResolver ({event}) ->
  if event.key is 'CapsLock' and event.keyCode is 8 and !event.ctrlKey and event.type is 'keydown'
    return 'backspace'
  if event.key is 'CapsLock' and event.keyCode is 8 and event.ctrlKey and event.type is 'keydown'
    return 'ctrl-backspace'
```
Not really familiar with coffee, so hopefully this syntax is correct.

**Comment by Ben3eeE** [comment] 2016-12-15 11:56
Hey, I tried to repro this on Ubuntu to see if we could add the workaround into `atom-keymap` and I was unable to.

@Gert-dev Did you only see this on Linux with the <kbd>Ctrl</kbd> modifier? It so it is possible that this was fixed in Atom 1.12.7 with the <kbd>Ctrl</kbd> modifier fix. Can you test it out and see if it works for you with the latest version?

@mattkang How did you install the colemak layout?

**Comment by Gert-dev** [comment] 2016-12-15 12:30
@Ben3eeE Thanks for the tip, I can confirm that the issue is fixed for me in Atom 1.12.7. Atom 1.12.6 still requires the fix listed by @mattkang specified above.

**Comment by mattkang** [comment] 2016-12-15 15:27
@Ben3eeE Just updated to Atom 1.12.7, and the issue persists for me. I installed the Colemak layout via [colemak.com](https://colemak.com/Windows). I use [Version with Caps Lock as Backspace](https://forum.colemak.com/topic/1621-colemak-for-windows-with-capslock-to-backspace/).

**Comment by 50Wliu** [comment] 2016-12-15 15:28
@mattkang and what is the output of `atom --version`?

**Comment by mattkang** [comment] 2016-12-15 15:30
@50Wliu 
```
Atom    : 1.12.7
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0
```

**Comment by JustinLewisSMA** [comment] 2017-01-12 23:47
Hi! I just installed 1.13.0 ia32 today and the Colemak caps issue exists.

**Comment by LennartCockx** [comment] 2017-03-17 13:58
I'm also unable to use the Colemak caps backspace in windows 10 using v1.15.0 x64

**Comment by mattkang** [comment] 2017-05-02 21:13
Updated temporary ``init.coffee`` fix:
```coffee
atom.keymaps.addKeystrokeResolver ({event}) ->
  if event.key is 'CapsLock' and event.keyCode is 8 and event.type is 'keydown'
    return 'backspace'
  if event.key is 'Delete' and event.keyCode is 8 and event.ctrlKey and event.type is 'keydown'
    return 'ctrl-backspace'
```
Fixes <kbd>Ctrl</kbd>+<kbd>Backspace</kbd> in v1.16.0.

**Comment by Ben3eeE** [comment] 2017-09-08 10:21
@mattkang Atom 1.19 upgraded Electron which might have resolved this issue for you. Can you confirm if it is working when using Atom 1.19 without the workaround or do you still see the same issue?

**Comment by BowenWang** [comment] 2017-09-11 20:23
Hi all,
I just downloaded the Atom editor from atom.io and install. I have a pretty similar issue. I use xmodmap to remap my CapsLock key to Backspace, and Backspace to Tab. It works in my linux.
But when I tried to use the Atom, I found that both Capslock(remap to Backspace in my system) and Backspace(remap to Tab in my system) are interpreted as Backspace.

Anyone knows how I can fix it?

Bowen

**Comment by mattkang** [comment] 2017-09-11 20:27
@Ben3eeE It appears this Backspace issue has been resolved! On Atom 1.19.3, and Backspace appears to function correctly without the use of the workaround.

**Comment by BowenWang** [comment] 2017-09-11 20:42
@mattkang Do you know how I can fix the problem I mentioned above?

**Comment by mattkang** [comment] 2017-09-11 20:47
@BowenWang The ``init.coffee`` fix I posted previously may work for you but will require editing.

To figure out what key commands are actually being triggered, you need to run this devtools console script:
`document.addEventListener('keydown', e => console.log(e), true)`

All the best!

**Comment by BowenWang** [comment] 2017-09-11 20:49
@mattkang All right, I will try it. Thanks!

Bowen

**Comment by Ben3eeE** [comment] 2017-09-11 20:52
@BowenWang If you need help to write the function you can ask on Discuss or the Atom slack.

* [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.

----

I'm going to close this issue out because it has been resolved with the Electron upgrade 🎉

**Closed by Ben3eeE** 2017-09-11 20:52 UTC
Labels: bug, needs-reproduction
