### ISSUE TITLE
Right ALT - diacritical letters problem "ó"

### ISSUE THREAD

**Issue by bazilazi** [atom/atom-keymap#103] opened 2015-11-12 14:44 UTC
It's hardly to use Atom with polish keyboard. The letters like "ó" (Right ALT + o) don't work.

**Comment by 50Wliu** [comment] 2015-11-12 18:08
Duplicate of atom/atom-keymap#35 and atom/atom-keymap#37, please subscribe there for updates.  Also try installing the [keyboard-localization](https://atom.io/package/keyboard-localization) package.

**Closed by 50Wliu** 2015-11-12 18:08 UTC
