### ISSUE TITLE
Multiple modifiers are not recognized correctly with non-latin characters due to uppercase checking

### ISSUE THREAD

**Issue by issacgerges** [atom/atom-keymap#237] opened 2018-12-21 22:09 UTC
*Edit by @rsese to mention Jason's [repro details](https://github.com/atom/atom-keymap/issues/237#issuecomment-461249081)*

> I see this issue using Atom 1.36.0-nightly11 on macOS 10.14.2.
> 
> ### Steps to reproduce
> I can reproduce it as follows:
> 
> 1. Open two tabs in Atom
> 2. Turn on the keybinding resolver so you can see how keybindings are being interpreted. In the command palette, run `Key Binding Resolver: Toggle`.
> 3. Hit command+shift+[ to move to the previous tab (i.e., previous pane item)
> 
> **Expected behavior**: In the Key Binding Resolver, you should see that the keystroke resolves to command+shift+[ and Atom should focus the previous tab (i.e., previous pane item).
> 
> **Actual behavior**: In the Key Binding Resolver, you see that the keystroke incorrectly resolves to command+[, which triggers the `Editor: Outdent Selected Rows` command.
> 
> ### Demo
> In the gif below, I have [Mouseposé](https://mac.softpedia.com/get/Utilities/Boinx-Mousepose.shtml) enabled to show which keys are being pressed. We can see Mouseposé showing command+shift+[ and command+shift+] being pressed, and we can see Atom interpreting them as command+[ and command+]. (See Atom's Key Binding Resolver output in the bottom left corner of the Atom window.)
> 
> ![demo](https://user-images.githubusercontent.com/2988/52383629-2c414e00-2a48-11e9-8375-a06ed83809b6.gif)

---

### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

When using multiple modifiers, for example Command+Shift+], `atom-keymap` will only recognize `cmd+]`. In these cases keymaps including keycodes for the latter will be caught by the former.

### Steps to Reproduce

1. Register a keymap for keycode `cmd+[`
2. Press Command+Shift+[

**Expected behavior:** The supplied event isn't dispatched

**Actual behavior:** The supplied event is dispatched

**Reproduces how often:** Consistently

### Additional Information

The issue seems to be caused by a check here: https://github.com/atom/atom-keymap/blob/1cb3a7a7fb9b9cb1acd3d2f2234593abfe098015/src/helpers.coffee#L248
Specifically `isUpperCaseCharacter` rules out the keystroke since `'['` is equal to `'['. toLowerCase()`. It may be worth including a check for `isNonCased` that explicitly checks if `key.toUpperCase() === key. toLowerCase()`

**Comment by issacgerges** [comment] 2018-12-21 22:13
It's also incredibly likely this was never hit in the past since Chromium used to report these keys as their shifted version when shit+command were pressed. This recently changed, although I can't find the Chromium ticket. Now, these are reported as their unsifted versions if both command and shift are pressed.

**Comment by rsese** [comment] 2019-01-09 20:57
Thanks for the report @issacgerges :bow:  I might be misunderstanding, but I wasn't able to reproduce on 1.34.0 with macOS 10.12.6.  I added this to my keymap:

```cson
'body':
 'cmd-{': 'unset!'

'atom-text-editor':
 'cmd-[': 'core:move-down'
```

I added that first one because otherwise in step 2 from your repro steps, Atom will show the previous pane on macOS.  But now if I follow your step 2, nothing happens.

Also what version of Atom are you running (`atom -v`)?

**Comment by VerteDinde** [comment] 2019-01-11 16:42
Hey @rsese! I actually think I'm seeing this too - we just upgraded to Electron 3 with Chromium 66, and I noticed that our shortcut for `cmd+plus` now only works if I type in `cmd+shift+plus`. Changing the shortcut to `cmd+=` works.

I'm running atom-keymap: 8.2.12. Happy to give more info if needed.

**Comment by rsese** [comment] 2019-01-17 21:39
@VerteDinde - are running Atom on Arch Linux?  We're not on Electron 3 yet, that's being worked on in https://github.com/atom/atom/pull/18603 (we can mention this issue there).

**Comment by rsese** [comment] 2019-02-06 22:21
@issacgerges @VerteDinde - the Electron 3 upgrade for Atom will be in the upcoming 1.36 beta release.  If you can reproduce there can you let us know if you can reproduce the problem there?

**Comment by rsese** [comment] 2019-02-06 22:53
One of our maintainers is seeing this on our nightly release which is on Electron 3, going to reopen.  Thanks again for the heads up @issacgerges @VerteDinde :v:

**Comment by jasonrudolph** [comment] 2019-02-07 00:54
I see this issue using Atom 1.36.0-nightly11 on macOS 10.14.2.

### Steps to reproduce

I can reproduce it as follows:

1. Open two tabs in Atom
2. Turn on the keybinding resolver so you can see how keybindings are being interpreted. In the command palette, run `Key Binding Resolver: Toggle`.
3. Hit <kbd>command</kbd>+<kbd>shift</kbd>+<kbd>[</kbd> to move to the previous tab (i.e., previous pane item)

**Expected behavior**: In the Key Binding Resolver, you should see that the keystroke resolves to <kbd>command</kbd>+<kbd>shift</kbd>+<kbd>[</kbd> and Atom should focus the previous tab (i.e., previous pane item).

**Actual behavior**: In the Key Binding Resolver, you see that the keystroke incorrectly resolves to <kbd>command</kbd>+<kbd>[</kbd>, which triggers the `Editor: Outdent Selected Rows` command.

### Demo

In the gif below, I have [Mouseposé](https://mac.softpedia.com/get/Utilities/Boinx-Mousepose.shtml) enabled to show which keys are being pressed. We can see Mouseposé showing <kbd>command</kbd>+<kbd>shift</kbd>+<kbd>[</kbd> and <kbd>command</kbd>+<kbd>shift</kbd>+<kbd>]</kbd> being pressed, and we can see Atom interpreting them as <kbd>command</kbd>+<kbd>[</kbd> and <kbd>command</kbd>+<kbd>]</kbd>. (See Atom's Key Binding Resolver output in the bottom left corner of the Atom window.)

![demo](https://user-images.githubusercontent.com/2988/52383629-2c414e00-2a48-11e9-8375-a06ed83809b6.gif)

**Closed** 2019-02-18 01:52 UTC
Labels: d ⬆️, i ⬆️, triaged, v ⬆️
