### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by michaeljcalkins** [atom/atom-keymap#64] opened 2015-01-08 18:20 UTC
```
c:\Users\Michael J. Calkins\AppData\Local\atom\app-0.166.0\resources\app\node_modules\text-buffer\lib\text-buffer.js:387
Hide Stack Trace
TypeError: Cannot read property 'length' of undefined
  at TextBuffer.module.exports.TextBuffer.lineLengthForRow (c:\Users\Michael J. Calkins\AppData\Local\atom\app-0.166.0\resources\app\node_modules\text-buffer\lib\text-buffer.js:387:29)
  at TextBuffer.module.exports.TextBuffer.clipPosition (c:\Users\Michael J. Calkins\AppData\Local\atom\app-0.166.0\resources\app\node_modules\text-buffer\lib\text-buffer.js:939:53)
  at DisplayBuffer.module.exports.DisplayBuffer.screenPositionForBufferPosition (c:\Users\Michael J. Calkins\AppData\Local\atom\app-0.166.0\resources\app\src\display-buffer.js:1009:27)
  at DisplayBuffer.module.exports.DisplayBuffer.scrollToBufferPosition (c:\Users\Michael J. Calkins\AppData\Local\atom\app-0.166.0\resources\app\src\display-buffer.js:661:47)
  at TextEditor.module.exports.TextEditor.scrollToBufferPosition (c:\Users\Michael J. Calkins\AppData\Local\atom\app-0.166.0\resources\app\src\text-editor.js:2631:33)
  at GoToLineView.module.exports.GoToLineView.confirm (c:\Users\Michael J. Calkins\AppData\Local\atom\app-0.166.0\resources\app\node_modules\go-to-line\lib\go-to-line-view.js:116:14)
  at atom-text-editor.<anonymous> (c:\Users\Michael J. Calkins\AppData\Local\atom\app-0.166.0\resources\app\node_modules\go-to-line\lib\go-to-line-view.js:55:24)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (c:\Users\Michael J. Calkins\AppData\Local\atom\app-0.166.0\resources\app\src\command-registry.js:243:29)
  at c:\Users\Michael J. Calkins\AppData\Local\atom\app-0.166.0\resources\app\src\command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (c:\Users\Michael J. Calkins\AppData\Local\atom\app-0.166.0\resources\app\node_modules\atom-keymap\lib\keymap-manager.js:549:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (c:\Users\Michael J. Calkins\AppData\Local\atom\app-0.166.0\resources\app\node_modules\atom-keymap\lib\keymap-manager.js:391:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (c:\Users\Michael J. Calkins\AppData\Local\atom\app-0.166.0\resources\app\src\window-event-handler.js:167:20)
```

Windows 7
I pushed Ctrl + T and then Ctrl + Shift + T can't reproduce yet.
Then the red window to create the issue came up and my editor worked fine again.

**Comment by izuzak** [comment] 2015-06-10 12:50
Seem like a duplicate of https://github.com/atom/go-to-line/issues/19 -- closing this in favor of that one.

**Closed by izuzak** 2015-06-10 12:50 UTC
