### ISSUE TITLE
Slovak QWERTZ does not resolve keys correctly on macOS

### ISSUE THREAD

**Issue by selrond** [atom/atom-keymap#223] opened 2017-09-18 12:05 UTC
Coming from #37 

My keyboard layout is still not working.

I'm on __MB Pro with macOS Sierra 10.12.6 (16G29)__
Keyboard: __Slovak QWERTZ__
Atom version: __1.20.0__

When I press `cmd+'` (as recognized in Sublime Text), Atom sees `ctrl+§`. Or `cmd+/` (toggles comment in Sublime Text), Atom sees `cmd+'`.

Weird enough, macOS' native Keyboard viewer shows expected keys when typed, just Atom and VSCode seems to interpret them wrongly. 
I suspect Electron has something to do with it... 

I've already spent about 2 hours trying to resolve the issue, but I'm starting to lose my mind...

__Any suggestions?__

**Comment by Ben3eeE** [comment] 2017-09-18 12:08
Thank you for reaching out!

Can you give the output you get after you run the following script in the developer tools console and press the keys that are not working (`cmd+'` and `cmd+/`)
```
document.addEventListener('keydown', e => console.log(e), true)
```

**Comment by selrond** [comment] 2017-09-18 12:13
@Ben3eeE indeed:

`cmd+'`:
`KeyboardEvent {isTrusted: true, key: "Meta", code: "MetaLeft", location: 1, ctrlKey: false…}`
`KeyboardEvent {isTrusted: true, key: "§", code: "Quote", location: 0, ctrlKey: false…}`

`cmd+/`:
`KeyboardEvent {isTrusted: true, key: "Meta", code: "MetaLeft", location: 1, ctrlKey: false…}`
`KeyboardEvent {isTrusted: true, key: "Dead", code: "Equal", location: 0, ctrlKey: false…}`

**Comment by Ben3eeE** [comment] 2017-09-18 12:26
@selrond There is more information if you click the little triangle on the left of the output which will expand the output. Can you include the full event?

See this image for reference:
![image](https://user-images.githubusercontent.com/1058982/30541855-4e7e0710-9c7d-11e7-9d77-feedfd3a8d75.png)

Thank you!

**Comment by selrond** [comment] 2017-09-18 12:33
@Ben3eeE oh well, I thought you only need the short output.

`cmd+'`:
![image](https://user-images.githubusercontent.com/6603389/30542027-09cb1af8-9c7e-11e7-8203-19a9b8478829.png)
![image](https://user-images.githubusercontent.com/6603389/30542048-1dbab05a-9c7e-11e7-88d2-c54661700317.png)

`cmd+/`
![image](https://user-images.githubusercontent.com/6603389/30542085-3cb3ea3a-9c7e-11e7-8818-935d18a7b896.png)
![image](https://user-images.githubusercontent.com/6603389/30542101-49327f24-9c7e-11e7-810e-f8e62a68c677.png)

**Comment by Ben3eeE** [comment] 2017-09-18 12:42
Thank you for the additional information. This does indeed look like a bug in Electron/Chrome where the `KeyboardEvent.key` field for the event is not correct.

Looking at these events thought it does not seem that `cmd-'` should resolve to `ctrl-§`. Can you confirm what it resolves to by checking in the keybinding resolver? You can open the keybinding resolver using `cmd-.`.

We might be able to write a workaround for these issues using the Public keystroke resolver API. Is it only `cmd-'` and `cmd-/` that does not resolve correctly for you?

**Comment by selrond** [comment] 2017-09-18 12:53
@Ben3eeE 

> Looking at these events thought it does not seem that `cmd-'` should resolve to `ctrl-§`

It should I guess. When I log inpt in Sublime (using `sublime.log_input(True)`), it recognizes them as I would expect. 

As I mentioned, watching the native macOS' Keyboard Viewer, after pressing `cmd`, I see both `/` and `'` on expected places.

 > Can you confirm what it resolves to by checking in the keybinding resolver?

Yes it does, I've already tried that.

> Is it only cmd-' and cmd-/ that does not resolve correctly for you?

IDK yet, these are the two ones I found immediately as I use them quite heavily. 

I wanted to give Atom a chance and use it exclusively for a couple of days, but I'm quite frustrated. Key binding are crucial to me, and changing my habits just because they don't work seems like a non-reasonable time investment...

Thank you for your time, I hope this gets resolved.

**Comment by Ben3eeE** [comment] 2017-09-18 13:09
/cc: @ungb @rsese I'm going to need your help here since it's a macOS issue. I'll try on Windows as soon as I get the chance to.

**Comment by rsese** [comment] 2017-09-18 21:43
@selrond can you try this workaround by adding the following to your [init script](http://flight-manual.atom.io/hacking-atom/sections/the-init-file/)?

```
atom.keymaps.addKeystrokeResolver ({event}) ->
  if event.key is '§' and event.code is 'Quote' and event.metaKey and event.type isnt 'keyup'
    return 'cmd-\''
```

You need to restart Atom for the changes to take effect.  If that works out for you, you can do something similar for `cmd-/`.

We're also looking a bit more to figure out of this is a Chrome bug or not, but we're not sure yet.

**Comment by selrond** [comment] 2017-09-18 22:01
@rsese I've added this to `init.coffee`:

```coffeescript
atom.keymaps.addKeystrokeResolver ({event}) ->
  if event.key is '§' and event.code is 'Quote' and event.metaKey and event.type isnt 'keyup'
    return 'cmd-\''

atom.keymaps.addKeystrokeResolver ({event}) ->
  if event.key is 'Dead' and event.code is 'Equal' and event.metaKey and event.type isnt 'keyup'
    return 'cmd-\/'
```

It __is__ working!

However, I'd _really_ love to understand what's going on as this approach is unsustainable for me.

**Comment by ungb** [comment] 2017-09-18 22:30
I was able to repro based on the repro steps, but I'm unclear what the expected behavior should be?

based on this image of Slovak Qwerty:
![image](https://user-images.githubusercontent.com/5624870/30567230-483b872c-9c84-11e7-8044-87a59351177e.png)

In Slovak Qwerty on mac on atom 1.20:

when I hit `cmd+shift+[` -> `cmd+/`

when I hit `cmd+/` -> `cmd+-` 
when I hit `cmd+'` -> `cmd+§`

It's unclear to me what the expected behavior should be in this case, but currently, it seems to be respecting the keyboard layout.

**Comment by selrond** [comment] 2017-09-18 22:38
@ungb 
The layout you provided seems weird, here's a screenshot from my Keyboard Viewer: (I had to press <kbd>⌘</kbd>+<kbd>⌃</kbd>+<kbd>⇧</kbd>+<kbd>4</kbd> in order to capture the screenshot, but the keys are the same after holding down just <kbd>⌘</kbd>)

![image](https://user-images.githubusercontent.com/6603389/30567811-6bdb2d88-9cd2-11e7-8a68-6cfec5caa3d3.png)

**Comment by ungb** [comment] 2017-09-18 22:50
Ah, I see now.  I didn't know about the keyboard viewer and thought the keyboard layout was based on the image I found, but after opening the keyboard layout I'm seeing what you're seeing.



![repro](https://user-images.githubusercontent.com/5624870/30568245-f0a4db30-9c88-11e7-8fb7-b89ecf0a3f9b.gif)

**Comment by Ben3eeE** [comment] 2017-09-19 05:52
@selrond We understand that this is a bad issue. The keystroke resolver in your init script is a temporary workaround so you can continue working normally. If this is an issue in Chrome it will take a while before the fix reaches us.

@rsese I was chatting with @ungb this morning. We came up with some things to test to check expected behavior and where it is an issue

* Do other keys that change when pressing <kbd>⌘</kbd> resolve differently on this layout or is it a problem with all of them?
* Are there other layouts that behave this way and how do they resolve keys?
* What is the expected `KeyboardEvent.key` in this case based on how other keys and layouts resolve? What about based on the specification for `KeyboardEvent.key`?
* Is the dead key an issue with `keyboard-layout`?
* Is this a regression with the latest Electron update or has it always been there?
* Is this an issue on the latest stable release of Chrome?

Based on this we can move this issue to the respective repositories so they get resolved. @ungb I think this is something we should test when testing Electron upgrades.

**Comment by ungb** [comment] 2017-09-19 20:11
We were able to identify that this issue is related to chromium.  I tried the same keys on Chrome and on firefox and on firefox it's resolving correctly. 

I filed https://bugs.chromium.org/p/chromium/issues/detail?id=766800 on chromium and should be fixed once that bug is fixed.

**Comment by selrond** [comment] 2017-09-19 20:32
@ungb Thank you for your time dedicated to this issue! I really appreciate it.

**Comment by Ben3eeE** [comment] 2017-09-26 22:30
Seems like this issue is fixed in chromium M62. It might take a while before the fix reaches us. I think we can add a workaround in `atom-keymap` similar to the dvorak-qwerty workaround so the layout is working correctly until then.

Issue ref: https://bugs.chromium.org/p/chromium/issues/detail?id=747358
Unrelated note: Looks like we can the dvorak-qwerty workaround once we are on chromium M62 🎉

**Closed** 2017-09-28 19:56 UTC
Labels: blocked, bug, mac, triaged
