### ISSUE TITLE
keymap-manager: Display all possible commands, not just bound ones

### ISSUE THREAD

**Issue by crucialfelix** [atom/atom-keymap#136] opened 2016-05-22 06:46 UTC
keymap-manager should be able to display and search through all bindable commands.

We may know a command exists because it's in the command pallette, but we can't assign a keymap to it until we know what it's code name is.

Currently we have to open a console and type `atom.commands.registeredCommands` and scroll down to discover what the code name of a command is.

**Comment by lee-dohm** [comment] 2016-05-24 05:14
This is a duplicate of https://github.com/atom/settings-view/issues/165. You may want to subscribe there for updates.

Thanks for contributing!

**Closed by lee-dohm** 2016-05-24 05:14 UTC
