### ISSUE TITLE
Comment shortcut does not work with Mac's Dvorak - Qwerty ⌘ mode

### ISSUE THREAD

**Issue by drw158** [atom/atom-keymap#60] opened 2014-11-12 16:17 UTC
I use Mac's Dvorak - Qwerty ⌘ mode for my keyboard layout. Recently, Atom gained full support for this keyboard layout (yay!), but I found one shortcut not working...

When I try to comment something out in a CSS or JS file by using the `⌘` + `/` shortcut, nothing happens. All other shortcuts that I use work, including copy, paste, command palette, find, etc. All of them use the ⌘ key and they work.

I tried to disable my 3rd party packages, but it still didn't work.

I checked my keybindings, and commenting is indeed set to `⌘` + `/`.

I have no custom keybindings.

Changing my keyboard layout to US allows me to use the shortcut, so I know is has something to do with the Dvorak - Qwerty ⌘ mode.

Yosemite 10.10
Atom 0.145.0

**Comment by Ben3eeE** [comment] 2017-10-12 12:20
Duplicate of https://github.com/atom/keyboard-layout/issues/3

**Closed by Ben3eeE** 2017-10-12 12:20 UTC
